apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  creationTimestamp: "2022-10-25T22:34:59Z"
  finalizers:
  - finalizers.fluxcd.io
  - kommander.d2iq.io/gitrepository-apps
  - kommander.d2iq.io/kommander-catalog-repository
  generation: 1
  labels:
    kommander.d2iq.io/gitapps-gitrepository-type: catalog
    kommander.d2iq.io/gitrepository-type: catalog
  name: bigbang-catalog
  namespace: bigbang-catalog

spec:
  gitImplementation: go-git
  interval: 30s
  ref:
    branch: master
  timeout: 30s
  url: https://github.com/d2iq-ps/d2iq-ps-kommander-catalog.git