---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: software-factory-project
spec:
  chart:
    spec:
      chart: harbor
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: Helm
        namespace: software-factory-project
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: software-factory-project
  