---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: software-factory-project
spec:
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: charts.gitlab.io
        namespace: software-factory-project
      version: 6.5.1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  releaseName: gitlab
  valuesFrom:
    - kind: ConfigMap
      name: gitlab-6.5.1-defaults
  targetNamespace: software-factory-project
