apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
  namespace: bigbang
spec:
  chart:
    spec:
      chart: bigbang
      sourceRef:
        kind: GitRepository
        name: bigbang
        namespace: bigbang 
      version: 1.46.1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: bigbang
  targetNamespace: bigbang