apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: bigbang
      sourceRef:
        kind: HelmRepository
        name: bigbang
        namespace: ${releaseNamespace} 
      version: 1.46.1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: bigbang
  targetNamespace: ${releaseNamespace}