---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ghost
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: "https://charts.bitnami.com/bitnami"