---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bigbang
  namespace: ${releaseNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  #url: https://repo1.dso.mil/platform-one/big-bang/bigbang
  url: https://raw.githubusercontent.com/d2iq-ps/charts/experimental/
  interval: 5m