---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: software-factory-project
spec:
  chart:
    spec:
      chart: ghost
      sourceRef:
        kind: HelmRepository
        name: ghost
        namespace: software-factory-project
      version: 1.0.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: ghost
#  valuesFrom:
#    - kind: ConfigMap
 #     name: gitlab-6.5.1-defaults
  targetNamespace: software-factory-project