---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: software-factory-project
spec:
  chart:
    spec:
      chart: elasticsearch
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-charts-stable
        namespace: software-factory-project 
      version: 2.0.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: elasticsearch
  valuesFrom:
    - kind: ConfigMap
      name: elasticsearch-2.0.0-d2iq-defaults
  targetNamespace: software-factory-project
